# cargo-deny configuration for ClamReef Agent
# Compatible with recent cargo-deny versions

[graph]
# If true, metadata will be collected with `--all-features`
all-features = true

[advisories]
# Lint level for security vulnerabilities
vulnerability = "deny"
# Lint level for unmaintained crates
unmaintained = "warn"
# Lint level for yanked crates
yanked = "warn"
# Lint level for crates with security notices
notice = "warn"
# Advisory IDs to ignore
ignore = []

[licenses]
# Confidence threshold for detecting a license from license text
confidence-threshold = 0.8
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
# List of explicitly disallowed licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
# Lint level for when multiple versions of the same license are detected
copyleft = "warn"
# The default lint level for licenses not explicitly allowed or denied
default = "deny"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# List of crates that are allowed. Use with care!
allow = []
# List of crates to deny
deny = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []